# docker-compose.yml (Modified)
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      # DB 접속에 필요한 환경 변수를 설정합니다.
      - DB_USER=ADMIN
      - DB_PASSWORD=QPqpqp1010!!  # 여기에 실제 DB 비밀번호를 입력
      - TNS_ALIAS=fastapibackenddb  # 찾은 별칭을 입력했습니다!
      - TNS_ADMIN=/app/wallet # Docker 컨테이너 내의 Wallet 경로
    volumes:
      # OCI 서버에 있는 Wallet 파일을 컨테이너에 마운트합니다.
      - ./wallet:/app/wallet
