# .github/workflows/deploy.yml
name: Deploy to OCI
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-backend-template:latest

      - name: Deploy to OCI server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop and remove the old container
            docker stop fastapi-backend || true
            docker rm fastapi-backend || true

            # Pull the latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-backend-template:latest

            # Run the new container
            # DB_ADMIN_PASSWORD 환경 변수를 Secrets에서 가져옵니다.
            docker run -d --restart=always \
              --name fastapi-backend \
              -p 8000:8000 \
              -e TNS_ADMIN=/app/wallet \
              -e DB_PASSWORD=${{ secrets.DB_ADMIN_PASSWORD }} \
              -v /home/${{ secrets.OCI_USER }}/wallet:/app/wallet \
              ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-backend-template:latest
